# coding: utf-8

"""
    Engine by MoneyLion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.58.0
    Contact: help@engine.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.analytics_api import AnalyticsApi


class TestAnalyticsApi(unittest.TestCase):
    """AnalyticsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnalyticsApi()

    def tearDown(self) -> None:
        pass

    def test_get_lead_client_tags(self) -> None:
        """Test case for get_lead_client_tags

        Get lead client tags
        """
        pass

    def test_get_lead_events(self) -> None:
        """Test case for get_lead_events

        Get lead events
        """
        pass

    def test_get_lead_payouts(self) -> None:
        """Test case for get_lead_payouts

        Get lead payouts
        """
        pass


if __name__ == '__main__':
    unittest.main()
