# coding: utf-8

"""
    Engine by MoneyLion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.58.0
    Contact: help@engine.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.lead_employment_information import LeadEmploymentInformation

class TestLeadEmploymentInformation(unittest.TestCase):
    """LeadEmploymentInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LeadEmploymentInformation:
        """Test LeadEmploymentInformation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LeadEmploymentInformation`
        """
        model = LeadEmploymentInformation()
        if include_optional:
            return LeadEmploymentInformation(
                employer_name = '',
                employer_address = '',
                employer_address2 = '',
                employer_city = '',
                employer_phone = '',
                employer_state = '',
                employer_zip = '',
                job_title = '',
                months_employed = 56,
                direct_deposit = True,
                pay_date1 = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                pay_date2 = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return LeadEmploymentInformation(
        )
        """

    def testLeadEmploymentInformation(self):
        """Test LeadEmploymentInformation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
