# coding: utf-8

"""
    Engine by MoneyLion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.58.0
    Contact: help@engine.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.special_offer import SpecialOffer

class TestSpecialOffer(unittest.TestCase):
    """SpecialOffer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpecialOffer:
        """Test SpecialOffer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpecialOffer`
        """
        model = SpecialOffer()
        if include_optional:
            return SpecialOffer(
                uuid = '',
                name = '',
                desc = '',
                url = '',
                partner_name = '',
                partner_image_url = '',
                recommendation_score = 1.337,
                payout = 1.337,
                product_sub_type = 'credit_card',
                disclaimer = '',
                financial_institution_uuid = ''
            )
        else:
            return SpecialOffer(
                uuid = '',
                name = '',
                desc = '',
                url = '',
                partner_name = '',
                partner_image_url = '',
                product_sub_type = 'credit_card',
        )
        """

    def testSpecialOffer(self):
        """Test SpecialOffer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
