# coding: utf-8

"""
    Engine by MoneyLion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.58.0
    Contact: help@engine.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.ui_events_api import UIEventsApi


class TestUIEventsApi(unittest.TestCase):
    """UIEventsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UIEventsApi()

    def tearDown(self) -> None:
        pass

    def test_create_offer_display(self) -> None:
        """Test case for create_offer_display

        Record offer display
        """
        pass

    def test_create_session_init(self) -> None:
        """Test case for create_session_init

        Record new session
        """
        pass


if __name__ == '__main__':
    unittest.main()
