# coding: utf-8

"""
    Engine by MoneyLion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.58.0
    Contact: help@engine.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.vehicle_information import VehicleInformation

class TestVehicleInformation(unittest.TestCase):
    """VehicleInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VehicleInformation:
        """Test VehicleInformation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VehicleInformation`
        """
        model = VehicleInformation()
        if include_optional:
            return VehicleInformation(
                monthly_payment = 1.337,
                estimated_mileage = 1.337,
                vehicle_identification_number = '',
                vehicle_uuid = ''
            )
        else:
            return VehicleInformation(
        )
        """

    def testVehicleInformation(self):
        """Test VehicleInformation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
