# coding: utf-8

"""
    Engine by MoneyLion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.58.0
    Contact: help@engine.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.occupancy_type import OccupancyType

class TestOccupancyType(unittest.TestCase):
    """OccupancyType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOccupancyType(self):
        """Test OccupancyType"""
        # inst = OccupancyType()

if __name__ == '__main__':
    unittest.main()
