# coding: utf-8

"""
    Engine by MoneyLion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.58.0
    Contact: help@engine.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.loan_offer import LoanOffer

class TestLoanOffer(unittest.TestCase):
    """LoanOffer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LoanOffer:
        """Test LoanOffer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LoanOffer`
        """
        model = LoanOffer()
        if include_optional:
            return LoanOffer(
                uuid = '',
                product_type = 'credit_card',
                product_sub_type = 'credit_card',
                product_sub_type_disclaimer = '',
                url = '',
                originator = openapi_client.models.originator.Originator(
                    key = '', 
                    name = '', 
                    description = '', 
                    images = [
                        openapi_client.models.originator_image.OriginatorImage(
                            size_key = '', 
                            url = '', )
                        ], 
                    disclaimer = '', 
                    company_uuid = '', 
                    financial_institution_uuid = '', ),
                originator_id = '',
                pre_qualified = True,
                pre_approved = True,
                secured = True,
                co_applicant = True,
                sponsored = True,
                max_amount = 56,
                min_amount = 56,
                term_length = 56,
                term_unit = 'day',
                display_term_unit = '',
                term_description = '',
                max_apr = 1.337,
                min_apr = 1.337,
                mean_apr = 1.337,
                apr_type = 'variable',
                apr_description = '',
                fee_rate = 1.337,
                max_fee_rate = 1.337,
                min_fee_rate = 1.337,
                fee_fixed = 1.337,
                max_fee_fixed = 1.337,
                min_fee_fixed = 1.337,
                allow_prepayment = True,
                prepayment_fee = 1.337,
                monthly_payment = 1.337,
                max_monthly_payment = 1.337,
                min_monthly_payment = 1.337,
                monthly_payment_description = '',
                mean_monthly_payment = 1.337,
                max_total_payment = 1.337,
                min_total_payment = 1.337,
                mean_total_payment = 1.337,
                recommendation_score = 1.337,
                payout = 1.337,
                conversion_probability = 1.337,
                terms = '',
                amount_prefix = ''
            )
        else:
            return LoanOffer(
                uuid = '',
                product_type = 'credit_card',
                product_sub_type = 'credit_card',
                originator = openapi_client.models.originator.Originator(
                    key = '', 
                    name = '', 
                    description = '', 
                    images = [
                        openapi_client.models.originator_image.OriginatorImage(
                            size_key = '', 
                            url = '', )
                        ], 
                    disclaimer = '', 
                    company_uuid = '', 
                    financial_institution_uuid = '', ),
                pre_qualified = True,
                pre_approved = True,
                secured = True,
                co_applicant = True,
                sponsored = True,
                max_amount = 56,
                apr_type = 'variable',
                allow_prepayment = True,
        )
        """

    def testLoanOffer(self):
        """Test LoanOffer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
