# coding: utf-8

"""
    Engine by MoneyLion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.58.0
    Contact: help@engine.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.lead_mortgage_information import LeadMortgageInformation

class TestLeadMortgageInformation(unittest.TestCase):
    """LeadMortgageInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LeadMortgageInformation:
        """Test LeadMortgageInformation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LeadMortgageInformation`
        """
        model = LeadMortgageInformation()
        if include_optional:
            return LeadMortgageInformation(
                property_type = 'rent',
                property_value = 56,
                mortgage_balance = 56,
                lender_name = '',
                has_fha_loan = True,
                current_with_loan = True,
                property_status = 'own_outright',
                mortgage_type = 'purchase',
                mortgage_amount = 56,
                down_payment_amount = 56,
                property_state = '',
                property_county = '',
                property_address1 = '',
                property_address2 = '',
                property_zipcode = '',
                property_city = '',
                refinance_amount = 56,
                cash_out_amount = 56,
                occupancy_type = 'primary',
                refinance_type = 'cash_out',
                property_search_status = 'found',
                num_units = 56,
                closing_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                purchase_status = 'no_offer',
                purchase_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                monthly_hoa_fee = 1.337,
                mortgage_company = '',
                mortgage_escrow_amount = 1.337
            )
        else:
            return LeadMortgageInformation(
        )
        """

    def testLeadMortgageInformation(self):
        """Test LeadMortgageInformation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
