# coding: utf-8

"""
    Engine by MoneyLion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.58.0
    Contact: help@engine.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.card_purpose import CardPurpose

class TestCardPurpose(unittest.TestCase):
    """CardPurpose unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCardPurpose(self):
        """Test CardPurpose"""
        # inst = CardPurpose()

if __name__ == '__main__':
    unittest.main()
