# coding: utf-8

"""
    Engine by MoneyLion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.58.0
    Contact: help@engine.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.event_type import EventType

class TestEventType(unittest.TestCase):
    """EventType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventType(self):
        """Test EventType"""
        # inst = EventType()

if __name__ == '__main__':
    unittest.main()
