# coding: utf-8

"""
    Engine by MoneyLion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.58.0
    Contact: help@engine.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.refinance_loan_information import RefinanceLoanInformation

class TestRefinanceLoanInformation(unittest.TestCase):
    """RefinanceLoanInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RefinanceLoanInformation:
        """Test RefinanceLoanInformation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RefinanceLoanInformation`
        """
        model = RefinanceLoanInformation()
        if include_optional:
            return RefinanceLoanInformation(
                account_number = '',
                income_based_repayment = True,
                interest_rate = 1.337,
                loan_amount = 56,
                loan_servicer = '',
                loan_type = 'federal_student_loan',
                next_payment_amount = 1.337,
                next_payment_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return RefinanceLoanInformation(
        )
        """

    def testRefinanceLoanInformation(self):
        """Test RefinanceLoanInformation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
