# coding: utf-8

"""
    Engine by MoneyLion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.58.0
    Contact: help@engine.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.opened_event_data import OpenedEventData

class TestOpenedEventData(unittest.TestCase):
    """OpenedEventData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenedEventData:
        """Test OpenedEventData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenedEventData`
        """
        model = OpenedEventData()
        if include_optional:
            return OpenedEventData(
                product_type = 'credit_card'
            )
        else:
            return OpenedEventData(
        )
        """

    def testOpenedEventData(self):
        """Test OpenedEventData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
