# coding: utf-8

"""
    Engine by MoneyLion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.58.0
    Contact: help@engine.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.incentive_type import IncentiveType

class TestIncentiveType(unittest.TestCase):
    """IncentiveType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIncentiveType(self):
        """Test IncentiveType"""
        # inst = IncentiveType()

if __name__ == '__main__':
    unittest.main()
