# coding: utf-8

"""
    Engine by MoneyLion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.58.0
    Contact: help@engine.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.life_insurance_offer_details import LifeInsuranceOfferDetails

class TestLifeInsuranceOfferDetails(unittest.TestCase):
    """LifeInsuranceOfferDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LifeInsuranceOfferDetails:
        """Test LifeInsuranceOfferDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LifeInsuranceOfferDetails`
        """
        model = LifeInsuranceOfferDetails()
        if include_optional:
            return LifeInsuranceOfferDetails(
                policy_amount = 56,
                term_length = 56,
                term_unit = 'day',
                monthly_premium_amount = 1.337,
                annual_premium_amount = 1.337,
                semi_annual_premium_amount = 1.337,
                online_app_available = True,
                no_medical_test = True,
                package_type = 'basic',
                recommended = True,
                medical_exam = 'no_exam_if_qualified',
                policy_name = '',
                carrier_decision_type = 'instant',
                partner_quote_id = '',
                convert_to_permanent = True,
                child_rider = '',
                accelerated_death_benefit = True,
                waiver_of_premium = '',
                is_online_application = True,
                delivery_method = '',
                exam_required = ''
            )
        else:
            return LifeInsuranceOfferDetails(
                policy_amount = 56,
                monthly_premium_amount = 1.337,
        )
        """

    def testLifeInsuranceOfferDetails(self):
        """Test LifeInsuranceOfferDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
