# coding: utf-8

"""
    Engine by MoneyLion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.58.0
    Contact: help@engine.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.lead_action_type import LeadActionType
from openapi_client.models.reject_reason import RejectReason
from typing import Optional, Set
from typing_extensions import Self

class LeadAction(BaseModel):
    """
    LeadAction
    """ # noqa: E501
    uuid: StrictStr
    action_type: LeadActionType = Field(alias="actionType")
    action_date: datetime = Field(alias="actionDate")
    originator_key: Optional[StrictStr] = Field(default=None, alias="originatorKey")
    demand_sub_account_id: StrictInt = Field(alias="demandSubAccountId")
    reject_reason: Optional[RejectReason] = Field(default=None, alias="rejectReason")
    amount: Optional[StrictInt] = None
    origination_fee: Optional[StrictInt] = Field(default=None, alias="originationFee")
    offer_click_id: Optional[StrictInt] = Field(default=None, alias="offerClickId")
    created_at: datetime = Field(alias="createdAt")
    deleted_at: Optional[datetime] = Field(default=None, alias="deletedAt")
    __properties: ClassVar[List[str]] = ["uuid", "actionType", "actionDate", "originatorKey", "demandSubAccountId", "rejectReason", "amount", "originationFee", "offerClickId", "createdAt", "deletedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LeadAction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LeadAction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "actionType": obj.get("actionType"),
            "actionDate": obj.get("actionDate"),
            "originatorKey": obj.get("originatorKey"),
            "demandSubAccountId": obj.get("demandSubAccountId"),
            "rejectReason": obj.get("rejectReason"),
            "amount": obj.get("amount"),
            "originationFee": obj.get("originationFee"),
            "offerClickId": obj.get("offerClickId"),
            "createdAt": obj.get("createdAt"),
            "deletedAt": obj.get("deletedAt")
        })
        return _obj


