# coding: utf-8

"""
    Engine by MoneyLion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.58.0
    Contact: help@engine.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LeadActionType(str, Enum):
    """
    LeadActionType
    """

    """
    allowed enum values
    """
    INITIALIZED = 'initialized'
    API_REJECTED = 'api_rejected'
    API_APPROVED = 'api_approved'
    API_LISTING = 'api_listing'
    CLICKED_REFERRAL_LINK = 'clicked_referral_link'
    CLICKED_SPECIAL_OFFER_LINK = 'clicked_special_offer_link'
    SPECIAL_OFFER_CONVERSION = 'special_offer_conversion'
    APPLIED = 'applied'
    REJECTED = 'rejected'
    APPROVED = 'approved'
    LISTED = 'listed'
    FUNDED = 'funded'
    NOT_FUNDED = 'not_funded'
    CLICKED_CREDIT_CARD_OFFER_LINK = 'clicked_credit_card_offer_link'
    CLICKED_MORTGAGE_OFFER_LINK = 'clicked_mortgage_offer_link'
    CLICKED_SAVINGS_OFFER_LINK = 'clicked_savings_offer_link'
    LENDER_QUALIFIED_LEAD = 'lender_qualified_lead'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LeadActionType from a JSON string"""
        return cls(json.loads(json_str))


