# coding: utf-8

"""
    Engine by MoneyLion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.58.0
    Contact: help@engine.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LoanPurpose(str, Enum):
    """
    LoanPurpose
    """

    """
    allowed enum values
    """
    AUTO = 'auto'
    AUTO_PURCHASE = 'auto_purchase'
    AUTO_REFINANCE = 'auto_refinance'
    BABY = 'baby'
    BOAT = 'boat'
    BUSINESS = 'business'
    CAR_REPAIR = 'car_repair'
    COSMETIC = 'cosmetic'
    CREDIT_CARD_REFI = 'credit_card_refi'
    DEBT_CONSOLIDATION = 'debt_consolidation'
    EMERGENCY = 'emergency'
    ENGAGEMENT = 'engagement'
    GREEN = 'green'
    HOME_IMPROVEMENT = 'home_improvement'
    HOME_PURCHASE = 'home_purchase'
    HOME_REFI = 'home_refi'
    HOUSEHOLD_EXPENSES = 'household_expenses'
    LARGE_PURCHASES = 'large_purchases'
    LIFE_EVENT = 'life_event'
    MEDICAL_DENTAL = 'medical_dental'
    MOTORCYCLE = 'motorcycle'
    MOVING_RELOCATION = 'moving_relocation'
    OTHER = 'other'
    RV = 'rv'
    SPECIAL_OCCASION = 'special_occasion'
    STUDENT_LOAN = 'student_loan'
    STUDENT_LOAN_REFI = 'student_loan_refi'
    TAXES = 'taxes'
    UNKNOWN = 'unknown'
    VACATION = 'vacation'
    WEDDING = 'wedding'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LoanPurpose from a JSON string"""
        return cls(json.loads(json_str))


