# coding: utf-8

"""
    Engine by MoneyLion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.58.0
    Contact: help@engine.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RefinanceLoanType(str, Enum):
    """
    RefinanceLoanType
    """

    """
    allowed enum values
    """
    FEDERAL_STUDENT_LOAN = 'federal_student_loan'
    PRIVATE_STUDENT_LOAN = 'private_student_loan'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RefinanceLoanType from a JSON string"""
        return cls(json.loads(json_str))


