# coding: utf-8

"""
    Engine by MoneyLion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.58.0
    Contact: help@engine.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RejectReason(str, Enum):
    """
    RejectReason
    """

    """
    allowed enum values
    """
    LOW_FICO = 'low_fico'
    NO_FICO = 'no_fico'
    MAJOR_DEROGATORY = 'major_derogatory'
    UNDERWRITING_DECLINE = 'underwriting_decline'
    DEBT_TO_INCOME_RATIO = 'debt_to_income_ratio'
    NOT_IN_ACTIVE_STATE = 'not_in_active_state'
    INCORRECT_DATA_PROVIDED = 'incorrect_data_provided'
    DUPLICATE = 'duplicate'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RejectReason from a JSON string"""
        return cls(json.loads(json_str))


